ytd_search/urls.py
# from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include(('ytd_search_api.urls', 'core_app'), namespace='app_1')),
]

ytd_search_api/urls.py
from django.conf.urls import url
from .views import YtdTemplateViewSet, YtdApiViewset


urlpatterns = [
    url(r'home', YtdTemplateViewSet.as_view(), name='home_page'),
    url(r'ytd/', YtdApiViewset.as_view(), name='ytd_api')
]

ytd_search_api/models.py
from django.db import models

# Create your models here.

ytd_search_api/views.py
# django core import for template listing
from django.views.generic import TemplateView
# rest framework imports
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.status import (
    HTTP_201_CREATED, HTTP_200_OK, HTTP_400_BAD_REQUEST,
)
# youtube api imports
from .utils import youtube_search, json_serialization



class YtdTemplateViewSet(TemplateView):
    template_name = "index.html"

class YtdApiViewset(APIView):
    """
    ytd class for handling get and post request
    """
    permission_classes = [AllowAny, ]

    def get(self, request):
        context = {
            'data': 'noting here'
        }

        return Response(context, status=HTTP_200_OK)

    def post(self, request):
        q = request.data['q']
        context = {'message': 'data fetched successfully'}
        try:
            data_request = youtube_search(q)
            serialized_data = json_serialization(data_request[1])
            context.update({'data': serialized_data})
            return Response(context, status=HTTP_200_OK)
        except:
            context.update({'message': 'request error form StackAPi'})
            return Response(context, status=HTTP_400_BAD_REQUEST)

ytd_search_api/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


        <title>{% block title%}{% endblock%}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
        <style type="text/css">

        </style>
      </head>
  <body>
      <section class="container">
          <div class="column is-two-thirds">
            {% include 'messages.html' %}
            {% block content %}
            {% endblock %}
           </div>
       </section>
      {% block js %}
      {% endblock %}
    </body>
</html>

ytd_search_api/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Homepage {% endblock %}
{% block content %}
<script>
    var app = angular.module('myApp',  []);
    app.config(['$httpProvider', function ($httpProvider) {
        $httpProvider.defaults.xsrfCookieName = 'csrftoken';
        $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';
    }]);
    app.config(function ($interpolateProvider) {
        $interpolateProvider.startSymbol('{$');
        $interpolateProvider.endSymbol('$}');
    });
    app.controller("appController", function ($scope, $http) {
        $scope.search_q = ''
        $scope.search_query = function() {
		        $http({
			      method: 'POST',
			      url: `{% url 'app_1:ytd_api' %}`,
			      data: {"q": $scope.search_q}
		      }).then(function success(response) {
            if (response.status === 200 ) {
                  $scope.obtained_data = response.data['data'];
                }
               else {
                  alert("Sorry something went wrong");
               }
             }, function error(response) {
                if (response.status === 429 ) {
                  alert('Request limit exceeded , Try after sometime !!');
                }
              }
             );
	      }
    });
</script>

<section ng-app="myApp" ng-controller="appController">
  <div ng-show='!obtained_data'>
    <div class="w3-container w3-teal">
      <h2 class="center_align jumbotron">Welcome to YTD Api</h2>

    </div>
    <form class="w3-container">
      <label class="w3-text-teal w3-margin-top">Search bar: </label>
      <input type="search" ng-model='search_q' value=""
        class="w3-input w3-border w3-light-grey"
        placeholder="search youtube data">
      <button  class="w3-btn w3-blue-grey w3-margin-top" type="submit" ng-click="search_query()">Submit</button>
    </form>
  </div>
  <div class="" ng-show="obtained_data">
    <div class="w3-card-4" ng-repeat='data in obtained_data'>

      <header class="w3-container w3-light-grey">
        <h3>{$ data.title $}</h3>
      </header>

      <div class="w3-container">
        <p>Published at: {$ data.published_at | date $}</p>
        <p> Channel link: <a href="{$ data.channel_link $}">{$ data.channel_link $}</a></p>
        <hr>
        <img alt="img" class="w3-left w3-margin-right" ng-src="{$ data.image $}">
        <p> <b>Description :</b>{$ data.description $}</p>
      </div>
      <button class="w3-button w3-block w3-dark-grey" ><a href="{$ data.link $}"></a>Link</button>
      <br>
</div>
  </div>
</section>

{% endblock %}

ytd_search_api/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}